#!/bin/bash

psql -U ${LISTING_POSTGRES_USER} <<-END
    CREATE USER ${LISTING_DB_ANON_ROLE};
    GRANT USAGE ON SCHEMA ${LISTING_DB_SCHEMA} TO ${LISTING_DB_ANON_ROLE};
    ALTER DEFAULT PRIVILEGES IN SCHEMA ${LISTING_DB_SCHEMA} GRANT ALL ON TABLES TO ${LISTING_DB_ANON_ROLE};
    GRANT ALL ON ALL SEQUENCES IN SCHEMA ${LISTING_DB_SCHEMA} TO ${LISTING_DB_ANON_ROLE};
    GRANT ALL ON ALL TABLES IN SCHEMA ${LISTING_DB_SCHEMA} TO ${LISTING_DB_ANON_ROLE};
END